image: docker:latest

stages:
  - build
  - release
  - review

variables:
  CI_REGISTRY_IMAGE: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USERNAME --password-stdin $CI_REGISTRY

build:
  image: docker
  stage: build
  tags:
    - ci
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  except:
    - tags

release-image:
  stage: release
  tags:
    - ci
  only:
    - tags
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

.mycloud: &mycloud
  - echo $__PROJECT_NAME__
  - kubectl version
  - cd k8s/
  - sed -i "s/__CI_BUILD_REF_SLUG__/${CI_COMMIT_REF_SLUG}/" deployment.yaml ingress.yaml service.yaml
  - sed -i "s/__PROJECT_NAME__/${CI_PROJECT_NAME}/" deployment.yaml ingress.yaml service.yaml
  - sed -i "s/__PROJECT_GROUP_NAMESPACE__/${__PROJECT_GROUP_NAMESPACE__}/" deployment.yaml ingress.yaml service.yaml
  - sed -i "s/__DOCKER_IMAGE__/$CI_REGISTRY\/$CI_PROJECT_NAMESPACE\/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG/" deployment.yaml
  - |
    if kubectl get secrets -n $__PROJECT_GROUP_NAMESPACE__ | grep -q myregistry; then
      echo 'myregistry created'
    else
      kubectl create secret docker-registry myregistry --docker-server=$CI_REGISTRY --docker-username=$CI_REGISTRY_USERNAME --docker-password=$CI_REGISTRY_PASSWORD --docker-email=$CI_REGISTRY_EMAIL --namespace=$__PROJECT_GROUP_NAMESPACE__
      echo "docker registry created"
    fi

.staging_deploy: &staging_deploy
  image: lachlanevenson/k8s-kubectl:latest
  stage: review
  tags:
    - staging
  environment:
    name: review/$CI_COMMIT_REF_SLUG_NAME
    url: https://cms.drm-staging.gviet.vn
    on_stop: stop_review
  before_script: *mycloud
  script:
    - sed -i "s/__K8S_HOST__/dashboard-ns53-dev.sigmadrm.com/" ingress.yaml
    - |
      if kubectl apply -f deployment.yaml | grep -e "configured" -e "unchanged"; then
          echo "=> Patching deployment to force image update."
          kubectl patch -f deployment.yaml -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"ci-last-updated\":\"$(date +'%s')\"}}}}}"
      else
          echo "=> Deployment apply has changed the object, no need to force image update."
      fi
    - kubectl apply -f service.yaml || true
    - kubectl apply -f ingress.yaml
    - kubectl rollout status -f deployment.yaml
    - kubectl get all,ing -n $__PROJECT_GROUP_NAMESPACE__ -l app=${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}

stop_review:
  image: lachlanevenson/k8s-kubectl:latest
  stage: review
  before_script: []
  tags:
    - staging
  variables:
    GIT_STRATEGY: none
  when: manual
  only:
    - branches
  except:
    - master
    - tags
  environment:
    name: review/$CI_COMMIT_REF_SLUG_NAME
    action: stop
  script:
    - kubectl version
    - kubectl delete ing -n $CI_PROJECT_NAMESPACE -l app=${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}
    - kubectl delete all -n $CI_PROJECT_NAMESPACE -l app=${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}

deploy to staging:
  <<: *staging_deploy
  only:
    - develop
  except:
    - master
    - tags
