export const yearMap = {
  [(new Date().getFullYear() - 4).toString()]: (
    new Date().getFullYear() - 4
  ).toString(),
  [(new Date().getFullYear() - 3).toString()]: (
    new Date().getFullYear() - 3
  ).toString(),
  [(new Date().getFullYear() - 2).toString()]: (
    new Date().getFullYear() - 2
  ).toString(),
  [(new Date().getFullYear() - 1).toString()]: (
    new Date().getFullYear() - 1
  ).toString(),
  [new Date().getFullYear().toString()]: new Date().getFullYear().toString(),
};

export const monthMap = {
  1: 'January',
  2: 'February',
  3: 'March',
  4: 'April',
  5: 'May',
  6: 'June',
  7: 'July',
  8: 'August',
  9: 'September',
  10: 'October',
  11: 'November',
  12: 'December',
};

export const methodName = {
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  DELETE: 'DELETE',
};

export const countriesMap = {
  AD: 'Andorra',
  AE: 'United Arab Emirates',
  AF: 'Afghanistan',
  AG: 'Antigua and Barbuda',
  AI: 'Anguilla',
  AL: 'Albania',
  AM: 'Armenia',
  AO: 'Angola',
  AQ: 'Antarctica',
  AR: 'Argentina',
  AS: 'American Samoa',
  AT: 'Austria',
  AU: 'Australia',
  AW: 'Aruba',
  AX: 'Aland Islands',
  AZ: 'Azerbaijan',
  BA: 'Bosnia and Herzegovina',
  BB: 'Barbados',
  BD: 'Bangladesh',
  BE: 'Belgium',
  BF: 'Burkina Faso',
  BG: 'Bulgaria',
  BH: 'Bahrain',
  BI: 'Burundi',
  BJ: 'Benin',
  BL: 'Saint Barthelemy',
  BM: 'Bermuda',
  BN: 'Brunei Darussalam',
  BO: 'Bolivia (Plurinational State of)',
  BQ: 'Bonaire, Sint Eustatius and Saba',
  BR: 'Brazil',
  BS: 'Bahamas',
  BT: 'Bhutan',
  BV: 'Bouvet Island',
  BW: 'Botswana',
  BY: 'Belarus',
  BZ: 'Belize',
  CA: 'Canada',
  CD: 'Congo (Democratic Republic of the)',
  CF: 'Central African Republic',
  CG: 'Congo',
  CH: 'Switzerland',
  CI: "Cote D'ivoire",
  CK: 'Cook Islands',
  CL: 'Chile',
  CM: 'Cameroon',
  CN: 'China',
  CO: 'Colombia',
  CR: 'Costa Rica',
  CU: 'Cuba',
  CV: 'Cabo Verde',
  CW: 'Curacao',
  CY: 'Cyprus',
  CZ: 'Czechia',
  DE: 'Germany',
  DJ: 'Djibouti',
  DK: 'Denmark',
  DM: 'Dominica',
  DO: 'Dominican Republic',
  DZ: 'Algeria',
  EC: 'Ecuador',
  EE: 'Estonia',
  EG: 'Egypt',
  ER: 'Eritrea',
  ES: 'Spain',
  ET: 'Ethiopia',
  FI: 'Finland',
  FJ: 'Fiji',
  FK: 'Falkland Islands (Malvinas)',
  FM: 'Micronesia (Federated States of)',
  FO: 'Faroe Islands',
  FR: 'France',
  GA: 'Gabon',
  GB: 'United Kingdom of Great Britain and Northern Ireland',
  GD: 'Grenada',
  GE: 'Georgia',
  GF: 'French Guiana',
  GG: 'Guernsey',
  GH: 'Ghana',
  GI: 'Gibraltar',
  GL: 'Greenland',
  GM: 'Gambia',
  GN: 'Guinea',
  GP: 'Guadeloupe',
  GQ: 'Equatorial Guinea',
  GR: 'Greece',
  GS: 'South Georgia and The South Sandwich Islands',
  GT: 'Guatemala',
  GU: 'Guam',
  GW: 'Guinea-Bissau',
  GY: 'Guyana',
  HK: 'Hong Kong',
  HN: 'Honduras',
  HR: 'Croatia',
  HT: 'Haiti',
  HU: 'Hungary',
  ID: 'Indonesia',
  IE: 'Ireland',
  IL: 'Israel',
  IM: 'Isle of Man',
  IN: 'India',
  IO: 'British Indian Ocean Territory',
  IQ: 'Iraq',
  IR: 'Iran (Islamic Republic of)',
  IS: 'Iceland',
  IT: 'Italy',
  JE: 'Jersey',
  JM: 'Jamaica',
  JO: 'Jordan',
  JP: 'Japan',
  KE: 'Kenya',
  KG: 'Kyrgyzstan',
  KH: 'Cambodia',
  KI: 'Kiribati',
  KM: 'Comoros',
  KN: 'Saint Kitts and Nevis',
  KP: "Korea (Democratic People's Republic of)",
  KR: 'Korea (Republic of)',
  KW: 'Kuwait',
  KY: 'Cayman Islands',
  KZ: 'Kazakhstan',
  LA: "Lao People's Democratic Republic",
  LB: 'Lebanon',
  LC: 'Saint Lucia',
  LI: 'Liechtenstein',
  LK: 'Sri Lanka',
  LR: 'Liberia',
  LS: 'Lesotho',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  LV: 'Latvia',
  LY: 'Libya',
  MA: 'Morocco',
  MC: 'Monaco',
  MD: 'Moldova (Republic of)',
  ME: 'Montenegro',
  MF: 'Saint Martin (French Part)',
  MG: 'Madagascar',
  MH: 'Marshall Islands',
  MK: 'North Macedonia',
  ML: 'Mali',
  MM: 'Myanmar',
  MN: 'Mongolia',
  MO: 'Macao',
  MP: 'Northern Mariana Islands',
  MQ: 'Martinique',
  MR: 'Mauritania',
  MS: 'Montserrat',
  MT: 'Malta',
  MU: 'Mauritius',
  MV: 'Maldives',
  MW: 'Malawi',
  MX: 'Mexico',
  MY: 'Malaysia',
  MZ: 'Mozambique',
  NA: 'Namibia',
  NC: 'New Caledonia',
  NE: 'Niger',
  NF: 'Norfolk Island',
  NG: 'Nigeria',
  NI: 'Nicaragua',
  NL: 'Netherlands',
  NO: 'Norway',
  NP: 'Nepal',
  NR: 'Nauru',
  NU: 'Niue',
  NZ: 'New Zealand',
  OM: 'Oman',
  PA: 'Panama',
  PE: 'Peru',
  PF: 'French Polynesia',
  PG: 'Papua New Guinea',
  PH: 'Philippines',
  PK: 'Pakistan',
  PL: 'Poland',
  PM: 'Saint Pierre and Miquelon',
  PN: 'Pitcairn',
  PR: 'Puerto Rico',
  PS: 'Palestine, State of',
  PT: 'Portugal',
  PW: 'Palau',
  PY: 'Paraguay',
  QA: 'Qatar',
  RE: 'Reunion',
  RO: 'Romania',
  RS: 'Serbia',
  RU: 'Russian Federation',
  RW: 'Rwanda',
  SA: 'Saudi Arabia',
  SB: 'Solomon Islands',
  SC: 'Seychelles',
  SD: 'Sudan',
  SE: 'Sweden',
  SG: 'Singapore',
  SH: 'Saint Helena, Ascension and Tristan Da Cunha',
  SI: 'Slovenia',
  SJ: 'Svalbard and Jan Mayen',
  SK: 'Slovakia',
  SL: 'Sierra Leone',
  SM: 'San Marino',
  SN: 'Senegal',
  SO: 'Somalia',
  SR: 'Suriname',
  SS: 'South Sudan',
  ST: 'Sao Tome and Principe',
  SV: 'El Salvador',
  SX: 'Sint Maarten (Dutch Part)',
  SY: 'Syrian Arab Republic',
  SZ: 'Eswatini',
  TC: 'Turks and Caicos Islands',
  TD: 'Chad',
  TG: 'Togo',
  TH: 'Thailand',
  TJ: 'Tajikistan',
  TK: 'Tokelau',
  TL: 'Timor-Leste',
  TM: 'Turkmenistan',
  TN: 'Tunisia',
  TO: 'Tonga',
  TR: 'Turkey',
  TT: 'Trinidad and Tobago',
  TV: 'Tuvalu',
  TW: 'Taiwan (Province of China)',
  TZ: 'Tanzania, United Republic of',
  UA: 'Ukraine',
  UG: 'Uganda',
  UM: 'United States Minor Outlying Islands',
  US: 'United States of America',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VA: 'Holy See',
  VC: 'Saint Vincent and The Grenadines',
  VE: 'Venezuela (Bolivarian Republic of)',
  VG: 'Virgin Islands (British)',
  VI: 'Virgin Islands (U.S.)',
  VN: 'Viet Nam',
  VU: 'Vanuatu',
  WF: 'Wallis and Futuna',
  WS: 'Samoa',
  YE: 'Yemen',
  YT: 'Mayotte',
  ZA: 'South Africa',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
};

export const citiesMap = {
  'an giang': 'An Giang',
  'ba ria - vung tau': 'Bà Rịa - Vũng Tàu',
  'bac giang': 'Bắc Giang',
  'bac kan': 'Bắc Kạn',
  'bac lieu': 'Bạc Liêu',
  'bac ninh': 'Bắc Ninh',
  'ben tre': 'Bến Tre',
  'binh dinh': 'Bình Định',
  'binh duong': 'Bình Dương',
  'binh phuoc': 'Bình Phước',
  'binh thuan': 'Bình Thuận',
  'ca mau': 'Cà Mau',
  'can tho': 'Cần Thơ',
  'cao bang': 'Cao Bằng',
  'da nang': 'Đà Nẵng',
  'dak lak': 'Đắk Lắk',
  'dak nong': 'Đắk Nông',
  'dien bien': 'Điện Biên',
  'dong nai': 'Đồng Nai',
  'dong thap': 'Đồng Tháp',
  'gia lai': 'Gia Lai',
  'ha giang': 'Hà Giang',
  'ha nam': 'Hà Nam',
  'ha noi': 'Hà Nội',
  'ha tinh': 'Hà Tĩnh',
  'hai duong': 'Hải Dương',
  'hai phong': 'Hải Phòng',
  'hau giang': 'Hậu Giang',
  'ho chi minh': 'Hồ Chí Minh',
  'hoa binh': 'Hoà Bình',
  'hung yen': 'Hưng Yên',
  'khanh hoa': 'Khánh Hòa',
  'kien giang': 'Kiên Giang',
  'kon tum': 'Kon Tum',
  'lai chau': 'Lai Châu',
  'lam dong': 'Lâm Đồng',
  'lang son': 'Lạng Sơn',
  'lao cai': 'Lào Cai',
  'long an': 'Long An',
  'nam dinh': 'Nam Định',
  'nghe an': 'Nghệ An',
  'ninh binh': 'Ninh Bình',
  'ninh thuan': 'Ninh Thuận',
  'phu tho': 'Phú Thọ',
  'phu yen': 'Phú Yên',
  'quang binh': 'Quảng Bình',
  'quang nam': 'Quảng Nam',
  'quang ngai': 'Quảng Ngãi',
  'quang ninh': 'Quảng Ninh',
  'quang tri': 'Quảng Trị',
  'soc trang': 'Sóc Trăng',
  'son la': 'Sơn La',
  'tay ninh': 'Tây Ninh',
  'thai binh': 'Thái Bình',
  'thai nguyen': 'Thái Nguyên',
  'thanh hoa': 'Thanh Hóa',
  'thua thien hue': 'Thừa Thiên Huế',
  'tien giang': 'Tiền Giang',
  'tra vinh': 'Trà Vinh',
  'tuyen quang': 'Tuyên Quang',
  'vinh long': 'Vĩnh Long',
  'vinh phuc': 'Vĩnh Phúc',
  'yen bai': 'Yên Bái',
};

export const roleMap = {
  admin: 'Admin',
  merchant: 'Admin merchant',
  user: 'User',
};
export const roleMapForMerChant = {
  merchant: 'Admin merchant',
  user: 'User',
};
export const statusMap = {
  active: 'Active',
  inactive: 'Inactive',
};
export const domainType = {
  master: 'Master',
  native: 'Native',
  slave: 'Slave',
};
export const domainSoaEditAPI = {
  default: ' Default',
  increase: 'Increase',
  epoch: 'Epoch',
  off: 'Off',
};
export const recordType = {
  A: 'A',
  // AAAA: 'AAAA',
  // CNAME: 'CNAME',
  // MX: 'MX',
  // TXT: 'TXT',
  // PTR: 'PTR',
  // SRV: 'SRV',
  // SPF: 'SPF',
  // CAA: 'CAA',
  NS: 'NS',
  // LOC: 'LOC',
};

export const ispMap = {
  'vietnam posts and telecommunications group': 'VNPT',
  viettel: 'Viettel',
  'fpt telecom': 'FPT Telecom',
  'vietnam data communication company': 'Vietnam Data Communication Company',
  'saigon tourist cable television': 'Saigon Tourist Cable Television',
  'vietnam telecom national': 'Vietnam Telecom National',
  'adsl hni': 'ADSL HNI',
  'saigon postel corporation': 'Saigon Postel Corporation',
  'vietnam post and telecom corporation':
    'Vietnam Post and Telecom Corporation',
  'netnam corporation': 'Netnam Corporation',
  'cmc telecom infrastructure company': 'CMC Telecom Infrastructure Company',
  'vung dia chi ip cap cho dich vu iptv tai ha noi':
    'Vung dia chi IP cap cho dich vu IPTV tai Ha Noi',
  'mobifone service company region': 'Mobifone Service Company Region',
  'mo rong': 'Mo Rong',
  'vietnamobile telecommunications joint stock company':
    'Vietnamobile Telecommunications Joint Stock Company',
  'quang trung software city development company limited':
    'Quang Trung Software City Development Company Limited',
  'cung cap dich vu internet khach hang quan binh thanh':
    'Cung Cap Dich vu Internet Khach Hang Quan Binh Thanh',
  'htc international telecommunication joint stock company':
    'HTC International telecommunication joint stock company',
  'vietnam technology and telecommunication jsc':
    'Vietnam Technology and Telecommunication JSC',
  'vietnam internet network information center':
    'Vietnam Internet Network Information Center',
};
export const httpCodeMap = {
  200: 'OK',
  201: 'Created',
  202: 'Accepted',
  203: 'Non-Aut:horitative Information',
  204: 'No Content',
  205: 'Reset Content',
  206: 'Partial Content',
  207: 'Multi-Status',
  208: 'Already Reported',
  226: 'IM Used',
  300: 'Multiple Choices',
  301: 'Moved Permanently',
  302: 'Found ',
  303: 'See Other',
  304: 'Not Modified',
  305: 'Use Proxy',
  306: 'Switch Proxy',
  307: 'Temporary Redirect',
  308: 'Permanent Redirect',
};
export const trafficFlowTypeMap = {
  A: 'A',
};
export const trafficFlowValueMap = {
  // failover: 'Failover',
  geolocation: 'Geolocation',
  // ip_based: 'IP based',
  // multivalue_answer: 'Multivalue answer',
  // weighted: 'Weighted',
  round_robin: 'Round robin',
};
export const refreshMetrics = {
  5000: '5s',
  10000: '10s',
  15000: '15s',
  30000: '30s',
  60000: '1m',
};
